name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
        
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: build
      run: npm run build

    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: novenopatch
        author_email: novenosexta77@gmail.com
        force: false
        signoff: false
        message: ':memo: updated by o'
        add: "."
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
